version: "3"

services:
  shop_recruitment:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./shop_recruitment:/shop_recruitment
    environment:
      - SPRING_PROFILES_ACTIVE=production
    depends_on:
      - mongodb
    network_mode: "host"
  mongodb:
    container_name: mongodb
    restart: always
    image: "mongo:6.0.5"
    command: mongod --port 27020
    environment:
      - "MONGO_INITDB_ROOT_PASSWORD=secret"
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_DATABASE=shop"
    volumes:
      - "./init.js:/docker-entrypoint-initdb.d/init-mongo.js"
    network_mode: "host"